project:
  name: nt548-lab2-taskcat
  regions:
    - us-east-1
tests:
  infrastructure-test:
    template: infrastructure.yaml
    parameters:
      VpcCidr: 10.1.0.0/16
      KeyName: key
      InstanceType: t2.micro
